services:
  api:
    build: ./api
    ports:
      - "8080:8080"
    environment:
      - Cloudinary__CloudName=${CLOUDINARY_CLOUD}
      - Cloudinary__ApiKey=${CLOUDINARY_KEY}
      - Cloudinary__ApiSecret=${CLOUDINARY_SECRET}
    volumes:
      - ./api/database:/app/data
    restart: always

  frontend:
    build: ./docs
    ports:
      - "80:80"  
    restart: always
    depends_on:
      - api